<a href="https://colab.research.google.com/github/smsmorsalin/ML-Basics/blob/main/Basic_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
# 0D/scalar:

scalar = np.array(5)
print("scalar: ",scalar)
print("rank/array dimension: ", scalar.ndim)
print("shape", scalar.shape)

scalar:  5
rank/array dimension:  0
shape ()


In [ ]:
vector = np.array([2,4,5,6])
print("array: ",vector)
print("rank/No of axis/array dimension: ", vector.ndim)
print("shape", vector.shape)

# Note:
# 1D Tensor = Vector --> [2,3,4,5] and dimension of this vector is 4.(vector elements a.k.a dimension).
# array dimension and vector dimension both are different things.

array:  [2 4 5 6]
rank/No of axis/array dimension:  1
shape (4,)


In [ ]:
# 2D/Matrix:

matrix = np.array([[2,3,4],[2,1,4],[1,6,4]])
print("matrix",matrix)
print("rank/array dimension: ", matrix.ndim)
print("shape", matrix.shape)

matrix [[2 3 4]
 [2 1 4]
 [1 6 4]]
rank/array dimension:  2
shape (3, 3)


In [ ]:
# 3D:

# A 3D list with dimensions 2x2x3 (2 layers, 2 rows, 3 columns)
_3d_list = np.array([
    [[1, 2, 3], [4, 5, 6]],     # Layer 0
    [[7, 8, 9], [10, 11, 12]]   # Layer 1
])


print(_3d_list)
print("rank/array dimension: ", _3d_list.ndim)
print("shape", _3d_list.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
rank/array dimension:  3
shape (2, 2, 3)
